# Generated by Django 2.0.2 on 2018-06-04 18:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=254)),
                ('sexeAnimal', models.CharField(choices=[('M', 'Male'), ('F', 'Femelle')], max_length=1, verbose_name='sexe')),
                ('anneeNaissance', models.DateField(verbose_name='date de Naissance')),
                ('couleur', models.CharField(max_length=254)),
                ('dateAchat', models.DateField(verbose_name="date d'achat")),
                ('prixAchat', models.FloatField(verbose_name="prix d'achat")),
                ('temperament', models.CharField(max_length=254)),
                ('conformation', models.CharField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Animalevenmt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dateEvenement', models.DateTimeField(verbose_name="date de l'evenement")),
                ('observation', models.TextField(verbose_name='observation')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionon_cheptel.Animal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nomCategorie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom de la categorie')),
                ('libelleCategorie', models.CharField(blank=True, max_length=100, null=True, verbose_name='libelle de la categorie')),
                ('descriptionCategorie', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description de la categorie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cheptel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('secteur', models.CharField(max_length=100)),
                ('superficie', models.FloatField(verbose_name='superficie de la ferme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taille', models.FloatField(verbose_name='taille en cm')),
                ('poids', models.FloatField(verbose_name='Poids en kg')),
                ('sante', models.CharField(max_length=254)),
                ('datePrise', models.DateTimeField(verbose_name='date de prise')),
                ('photo', models.ImageField(upload_to='')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionon_cheptel.Animal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelleEvenement', models.CharField(blank=True, max_length=100, verbose_name='Libelle evenement')),
                ('evenement', models.CharField(blank=True, max_length=254, null=True, verbose_name='Type evenement ')),
                ('observation', models.CharField(blank=True, max_length=254, null=True, verbose_name='Observation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupeAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=100)),
                ('dateArrive', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Misebas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dateMisebas', models.DateTimeField(verbose_name='date de mise bas')),
                ('nombre', models.IntegerField()),
                ('description', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionon_cheptel.Animal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('Ville', models.CharField(max_length=100)),
                ('Pays', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProprietaireMoral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionon_cheptel.Proprietaire')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProprietairePersonne',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=254)),
                ('sexe', models.CharField(choices=[('M', 'Male'), ('F', 'Femelle')], max_length=1, verbose_name='sexe')),
                ('dateNaissace', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=100)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionon_cheptel.Proprietaire')),
            ],
            options={
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nomRace', models.CharField(blank=True, db_column='nomRace', max_length=100, verbose_name='Nom de la Race')),
                ('zoneProvenance', models.CharField(blank=True, db_column='zoneProvenance', max_length=100, null=True, verbose_name='Zone de Provenance')),
                ('tailleMax', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taille maximale')),
                ('poidsMax', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Poids maximal')),
                ('conformation', models.CharField(max_length=50)),
                ('carcasse', models.CharField(max_length=50)),
                ('categorie', models.ForeignKey(db_column='idCategorie', on_delete=django.db.models.deletion.PROTECT, to='gestionon_cheptel.Categorie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupeEmbouche',
            fields=[
                ('groupeanimal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestionon_cheptel.GroupeAnimal')),
                ('duree', models.IntegerField(verbose_name='durée en mois')),
                ('typeEmbouche', models.CharField(max_length=100, verbose_name="Type de l'embouche")),
            ],
            options={
                'abstract': False,
            },
            bases=('gestionon_cheptel.groupeanimal',),
        ),
        migrations.CreateModel(
            name='GroupeReproduction',
            fields=[
                ('groupeanimal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestionon_cheptel.GroupeAnimal')),
            ],
            options={
                'abstract': False,
            },
            bases=('gestionon_cheptel.groupeanimal',),
        ),
        migrations.AddField(
            model_name='proprietairemoral',
            name='representan3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proprietairemoral',
            name='representant1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proprietairemoral',
            name='representant2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupeanimal',
            name='cheptel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionon_cheptel.Cheptel'),
        ),
        migrations.AddField(
            model_name='cheptel',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionon_cheptel.Proprietaire'),
        ),
        migrations.AddField(
            model_name='animalevenmt',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionon_cheptel.Evenement'),
        ),
        migrations.AddField(
            model_name='animal',
            name='evenements',
            field=models.ManyToManyField(through='gestionon_cheptel.Animalevenmt', to='gestionon_cheptel.Evenement'),
        ),
        migrations.AddField(
            model_name='animal',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionon_cheptel.GroupeAnimal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionon_cheptel.Race'),
        ),
    ]
