# Generated by Django 2.0.6 on 2018-07-10 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionon_cheptel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='proprietairepersonne',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='proprietairemoral',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='proprietairemoral',
            name='id',
        ),
        migrations.RemoveField(
            model_name='proprietairemoral',
            name='proprietaire',
        ),
        migrations.RemoveField(
            model_name='proprietairemoral',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='proprietairepersonne',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='proprietairepersonne',
            name='proprietaire',
        ),
        migrations.RemoveField(
            model_name='proprietairepersonne',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='proprietairepersonne',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='proprietairemoral',
            name='proprietaire_ptr',
            field=models.OneToOneField(auto_created=True, default=201, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestionon_cheptel.Proprietaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proprietairepersonne',
            name='proprietaire_ptr',
            field=models.OneToOneField(auto_created=True, default=201, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestionon_cheptel.Proprietaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proprietairepersonne',
            name='user',
            field=models.ForeignKey(default=2014, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
